<?php 
	chong_pha_hoai();
?>
<?php 
	if($_GET['function']=="admin_logout")
	{
		unset($_SESSION['ky_danh__hhh']);
		unset($_SESSION['mat_khau__hhh']);
		gotoLink("index.php");
		exit();
	}
?>