<?php 
	chong_pha_hoai();
	$trinh_duyet_opera=trinh_duyet_opera();
	if($_GET['them_vao_gio__nnn']=="them_vao_gio__nnn")
	{
		//$_SESSION[$ten_danh_dau.''];
		include("function/gio_hang/xu_ly_session.php");
		trangtruoc();
		exit();
	}
	if($_GET['thamso']=="thoat")
	{
		include("function/dang_ky_dang_nhap/thoat.php");
		if($trinh_duyet_opera=="co")
		{
			//thongbao("đây là trình duyệt opera");
			$link=$_SERVER['HTTP_REFERER'];
			chuyentrang($link);
		}
		else 
		{
			trangtruoc();
		}
		exit();
	}
	if($_POST['cap_nhat_gio_hang__ggg']=="cap_nhat_gio_hang__ggg")
	{
		include("function/gio_hang/cap_nhat_gio_hang.php");
		trangtruoc();
		exit();
	}
	if($_POST['dang_ky_thanh_vien__vvv']=="dang_ky_thanh_vien__vvv")
	{
		include("function/dang_ky_dang_nhap/thuc_hien_dang_ky.php");
		trangtruoc();
		exit();
	}
	if($_POST['thanh_toan_don_hang__hhh']=="thanh_toan_don_hang__hhh")
	{
		//include("function/dang_ky_dang_nhap/thuc_hien_thanh_toan.php");
		include("function/gio_hang/thuc_hien_thanh_toan.php");
		trangtruoc();
		exit();
	}
	if($_POST['dang_nhap__ggg']=="dang_nhap__ggg")
	{
		include("function/dang_ky_dang_nhap/thuc_hien_dang_nhap.php");
		if($trinh_duyet_opera=="co")
		{
			//thongbao("đây là trình duyệt opera");
			$link=$_SERVER['HTTP_REFERER'];
			chuyentrang($link);
		}
		else 
		{
			trangtruoc();
		}
		exit();
	}
	if($_POST['gui_lien_he__abc']=="gui_lien_he__abc")
	{
		include("function/lien_he/thuc_hien_gui.php");
		trangtruoc();
		exit();
	}
	if($_POST['tv__lay_lai_mat_khau']=="tv__lay_lai_mat_khau")
	{
		include("function/dang_ky_dang_nhap/thuc_hien_lay_lai_mat_khau.php");
		trangtruoc();
		exit();
	}
	if($_POST['sua_thong_tin_ca_nhan']=="sua_thong_tin_ca_nhan")
	{
		include("function/dang_ky_dang_nhap/thuc_hien_sua_thong_tin_ca_nhan.php");
		trangtruoc();
		exit();
	}
?>